<?php
/**
 * División territorial de Garzón (Huila): barrios y veredas para el registro.
 * Fuente: Plan de Desarrollo "Garzón Adelante" 2024-2027 (Acuerdo 012 de 2024),
 * verificación del 6 de octubre de 2026 (Excel de la campaña): 107 unidades
 * urbanas, 12 corregimientos (centros poblados) y 93 veredas y sectores.
 *
 * [nombre, tipo, clase, grupo]. Los nombres son únicos: cuando una vereda se
 * llama igual que un barrio o que su centro poblado se le agrega "(vereda)".
 * Se cargan con "Actualizar plataforma" (no borra ni cambia las zonas en uso).
 */
const ZONAS_GARZON = [
    // Zona Norte
    ['San Isidro', 'urbano', 'Barrio', 'Zona Norte'],
    ['Bajo Sartenejo', 'urbano', 'Barrio', 'Zona Norte'],
    ['Valle del Casa Loma', 'urbano', 'Barrio', 'Zona Norte'],
    ['El Origen', 'urbano', 'Urbanización', 'Zona Norte'],
    // Zona Oriental
    ['Independencia', 'urbano', 'Barrio', 'Zona Oriental'],
    ['Las Colinas', 'urbano', 'Barrio', 'Zona Oriental'],
    ['Orquídea Real', 'urbano', 'Barrio', 'Zona Oriental'],
    // Zona Sur
    ['Las Mercedes', 'urbano', 'Barrio', 'Zona Sur'],
    ['Los Olivos', 'urbano', 'Barrio', 'Zona Sur'],
    ['El Progreso', 'urbano', 'Barrio', 'Zona Sur'],
    ['Los Pinos', 'urbano', 'Barrio', 'Zona Sur'],
    ['Villa Deportiva', 'urbano', 'Otro desarrollo urbano', 'Zona Sur'],
    // Zona Centro
    ['Centro', 'urbano', 'Barrio', 'Zona Centro'],
    ['Providencia', 'urbano', 'Barrio', 'Zona Centro'],
    ['Méndez', 'urbano', 'Barrio', 'Zona Centro'],
    // Zona Centro Occidente
    ['Rodrigo Lara Bonilla', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['Las Américas', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['San Vicente de Paúl', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['Juan Pablo II', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['Agustín Sierra', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['El Carmen', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['Santa Teresa', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['La Gaitana', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['El Rosario', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['El Jardín', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['El Obrero', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['Juan Pablo I', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    ['La Florida', 'urbano', 'Barrio', 'Zona Centro Occidente'],
    // Zona Centro Oriental
    ['Bosque de Cantabria', 'urbano', 'Urbanización', 'Zona Centro Oriental'],
    ['Nueva Holanda', 'urbano', 'Urbanización', 'Zona Centro Oriental'],
    ['Los Canelos', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['El Monasterio', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Santa Clara', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Nazareth', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['San Cayetano', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Primavera', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Calima', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Los Andes', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Los Laureles', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Villa Laura', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    ['Ciudadela Sabambu', 'urbano', 'Barrio', 'Zona Centro Oriental'],
    // Zona Centro Nor-Oriental
    ['La Carolina', 'urbano', 'Barrio', 'Zona Centro Nor-Oriental'],
    ['Jorge Enrique Pulido', 'urbano', 'Barrio', 'Zona Centro Nor-Oriental'],
    ['Villa Sol', 'urbano', 'Barrio', 'Zona Centro Nor-Oriental'],
    ['Villa Karol', 'urbano', 'Barrio', 'Zona Centro Nor-Oriental'],
    ['Mega Colegio', 'urbano', 'Equipamiento/Referencia urbana', 'Zona Centro Nor-Oriental'],
    ['Tochere', 'urbano', 'Condominio', 'Zona Centro Nor-Oriental'],
    ['Bosque del Caracolí', 'urbano', 'Conjunto cerrado', 'Zona Centro Nor-Oriental'],
    ['Torres de San Felipe', 'urbano', 'Proyecto de vivienda VIS', 'Zona Centro Nor-Oriental'],
    ['Castalia', 'urbano', 'Sector', 'Zona Centro Nor-Oriental'],
    ['Sagrada Familia', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    ['Riveras de Garzón', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    ['Nueva Floresta', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    ['Prado Alto', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    ['Reservas de Garzón', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    ['San Sebastián', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    ['La Floresta', 'urbano', 'Urbanización', 'Zona Centro Nor-Oriental'],
    // Zona Centro Occidental
    ['Los Comuneros', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    ['La Libertad', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    ['Veinte de Julio', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    ['Julio Bahamón', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    ['Chapinero', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    ['Granjas A', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    ['Los Nogales', 'urbano', 'Barrio', 'Zona Centro Occidental'],
    // Zona Centro Sur Oriental
    ['Las Granjas', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Limonar', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villa Garzón', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villas Café', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Los Samanes', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villa Prado', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Fundadores', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Las Vegas', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Aguazul', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['5 de Noviembre', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villa Constanza', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Nuevo Horizonte', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Los Guaduales III', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Álamos', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Nueva Colombia', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villa Francia', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villa Alejandra', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Brisas del Sur', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Villas del Café', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Las Palmeras', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Los Guaduales I', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Los Guaduales II', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['La Fortaleza', 'urbano', 'Urbanización', 'Zona Centro Sur Oriental'],
    ['Cerros', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Pío XII', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['El Bosque', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Termitas', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Minuto de Dios', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Ciudad Real', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['El Universitario', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Samaritanos', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['El Fontanar', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Las Orquídeas', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Santa Lucía', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Canadá', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['María Auxiliadora', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Luis Carlos Galán', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['Las Palmas', 'urbano', 'Barrio', 'Zona Centro Sur Oriental'],
    ['San José Residencial', 'urbano', 'Finca/Desarrollo residencial', 'Zona Centro Sur Oriental'],
    ['Reservas del Oriente', 'urbano', 'Urbanización', 'Zona Centro Sur Oriental'],
    ['Bosques del Café', 'urbano', 'Urbanización', 'Zona Centro Sur Oriental'],
    ['Octavio Martínez', 'urbano', 'Urbanización', 'Zona Centro Sur Oriental'],
    ['San Carlos', 'urbano', 'Urbanización', 'Zona Centro Sur Oriental'],
    // Corregimiento Descanso
    ['Descanso', 'rural', 'Centro poblado', 'Corregimiento Descanso'],
    ['Filo de Guayabal', 'rural', 'Vereda', 'Corregimiento Descanso'],
    ['La Orquídea', 'rural', 'Vereda', 'Corregimiento Descanso'],
    ['El Descanso', 'rural', 'Vereda', 'Corregimiento Descanso'],
    ['Nuevo Horizonte (vereda)', 'rural', 'Vereda', 'Corregimiento Descanso'],
    ['La Aurora', 'rural', 'Vereda', 'Corregimiento Descanso'],
    ['Los Robles', 'rural', 'Vereda', 'Corregimiento Descanso'],
    // Corregimiento El Mesón
    ['El Mesón', 'rural', 'Centro poblado', 'Corregimiento El Mesón'],
    ['La Cabaña', 'rural', 'Vereda', 'Corregimiento El Mesón'],
    ['El Mesón (vereda)', 'rural', 'Vereda', 'Corregimiento El Mesón'],
    ['Los Pinos (vereda)', 'rural', 'Vereda', 'Corregimiento El Mesón'],
    ['Las Mercedes (vereda)', 'rural', 'Vereda', 'Corregimiento El Mesón'],
    ['La Cañada', 'rural', 'Vereda', 'Corregimiento El Mesón'],
    // Corregimiento El Recreo
    ['El Recreo', 'rural', 'Centro poblado', 'Corregimiento El Recreo'],
    ['Primavera (vereda)', 'rural', 'Vereda', 'Corregimiento El Recreo'],
    ['Mesitas', 'rural', 'Vereda', 'Corregimiento El Recreo'],
    ['Pan de Azúcar', 'rural', 'Vereda', 'Corregimiento El Recreo'],
    ['El Recreo (vereda)', 'rural', 'Vereda', 'Corregimiento El Recreo'],
    // Corregimiento La Jagua
    ['La Jagua', 'rural', 'Centro poblado', 'Corregimiento La Jagua'],
    ['La Jagua (vereda)', 'rural', 'Vereda', 'Corregimiento La Jagua'],
    // Corregimiento Majo
    ['Majo', 'rural', 'Centro poblado', 'Corregimiento Majo'],
    ['Balseadero', 'rural', 'Vereda', 'Corregimiento Majo'],
    ['Alto Sartenejo', 'rural', 'Vereda', 'Corregimiento Majo'],
    ['Majo (vereda)', 'rural', 'Vereda', 'Corregimiento Majo'],
    ['El Barzal', 'rural', 'Vereda', 'Corregimiento Majo'],
    ['Jagualito', 'rural', 'Vereda', 'Corregimiento Majo'],
    ['Sector Huacanas', 'rural', 'Sector de vereda', 'Corregimiento Majo'],
    // Corregimiento Paraíso
    ['Paraíso', 'rural', 'Centro poblado', 'Corregimiento Paraíso'],
    ['Los Guaduales', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Potrerillos', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Filo de Pompeya', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['El Paraíso', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Villa Hermosa', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Buenos Aires', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['La Soledad', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Monserrate', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['El Progreso (vereda)', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Las Brisas', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Paloquemao', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['El Balseral', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['Los Milagros', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    ['San José', 'rural', 'Vereda', 'Corregimiento Paraíso'],
    // Corregimiento Providencia
    ['Providencia (centro poblado)', 'rural', 'Centro poblado', 'Corregimiento Providencia'],
    ['San Rafael', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['La Florida (vereda)', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['Sector Filo Rico', 'rural', 'Sector de vereda', 'Corregimiento Providencia'],
    ['Las Delicias', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['Vega de Platanares', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['El Líbano', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['Providencia (vereda)', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['Filo de Platanares', 'rural', 'Vereda', 'Corregimiento Providencia'],
    ['Nueva Floresta (vereda)', 'rural', 'Vereda', 'Corregimiento Providencia'],
    // Corregimiento Caguancito
    ['Caguancito', 'rural', 'Centro poblado', 'Corregimiento Caguancito'],
    ['El Mirador', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['La Ulama', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['Caguancito (vereda)', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['Mocoa', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['Puerto Alegría', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['Alto San Isidro', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['El Caguán', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['Panorama', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    ['El Socorro', 'rural', 'Vereda', 'Corregimiento Caguancito'],
    // Corregimiento San Antonio del Pescado
    ['San Antonio del Pescado', 'rural', 'Centro poblado', 'Corregimiento San Antonio del Pescado'],
    ['La Esperanza', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['La Trinidad', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['San Antonio', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['Sector Las Mercedes', 'rural', 'Sector de vereda', 'Corregimiento San Antonio del Pescado'],
    ['Unión Aguacaliente', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['El Viso', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['San Pedro', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['Sector La Ceiba', 'rural', 'Sector de vereda', 'Corregimiento San Antonio del Pescado'],
    ['El Rosario (vereda)', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['San Luis', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['Campo Bello', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['Santa Helena', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['Albania', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    ['El Pescado', 'rural', 'Vereda', 'Corregimiento San Antonio del Pescado'],
    // Corregimiento San Gerardo
    ['San Gerardo', 'rural', 'Centro poblado', 'Corregimiento San Gerardo'],
    ['Bellavista', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['San Gerardo (vereda)', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['Las Palmitas', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['San Miguel', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['Alejandría', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['El Cedral', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['El Batán', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    ['Los Alpes', 'rural', 'Vereda', 'Corregimiento San Gerardo'],
    // Corregimiento Santa Marta
    ['Santa Marta', 'rural', 'Centro poblado', 'Corregimiento Santa Marta'],
    ['Alto Fátima', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Santa Marta (vereda)', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['La Esmeralda', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Los Sauces', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Fátima', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Claros', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Puerto El Oasis', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Agua Blanca', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    ['Villa Rica', 'rural', 'Vereda', 'Corregimiento Santa Marta'],
    // Corregimiento Zuluaga
    ['Zuluaga', 'rural', 'Centro poblado', 'Corregimiento Zuluaga'],
    ['Miraflores', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['Los Medios', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['La Pita', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['La Azulita', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['Zuluaga (vereda)', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['Zuluaguita', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['Villa Florida', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
    ['El Vergel', 'rural', 'Vereda', 'Corregimiento Zuluaga'],
];
