<?php
/**
 * Barrios, veredas y corregimientos de Garzón (Huila) para el registro.
 * Fuente: Excel "División territorial de Garzón 2026" de la campaña, columnas
 * Nombre y Clasificación de las hojas Urbano_actual, Rural_actual y
 * PBOT_94_barrios (de esta última solo los que no están en Urbano_actual).
 *
 * [nombre, clasificación]. El nombre va tal cual el Excel: un mismo nombre puede
 * ser barrio y vereda (Las Mercedes) o corregimiento y vereda (La Jagua); los
 * distingue la clasificación. "Centro poblado / corregimiento" se guarda como
 * Corregimiento y "Asentamiento subnormal…" como Asentamiento.
 * Se cargan con "Actualizar plataforma" (ver zonas_reemplazar en esquema.php).
 */
const ZONAS_GARZON = [
    ['San Isidro', 'Barrio'],
    ['Bajo Sartenejo', 'Barrio'],
    ['Valle del Casa Loma', 'Barrio'],
    ['El Origen', 'Urbanización'],
    ['Independencia', 'Barrio'],
    ['Las Colinas', 'Barrio'],
    ['Orquídea Real', 'Barrio'],
    ['Las Mercedes', 'Barrio'],
    ['Los Olivos', 'Barrio'],
    ['El Progreso', 'Barrio'],
    ['Los Pinos', 'Barrio'],
    ['Villa Deportiva', 'Otro desarrollo urbano'],
    ['Centro', 'Barrio'],
    ['Providencia', 'Barrio'],
    ['Méndez', 'Barrio'],
    ['Rodrigo Lara Bonilla', 'Barrio'],
    ['Las Américas', 'Barrio'],
    ['San Vicente de Paúl', 'Barrio'],
    ['Juan Pablo II', 'Barrio'],
    ['Agustín Sierra', 'Barrio'],
    ['El Carmen', 'Barrio'],
    ['Santa Teresa', 'Barrio'],
    ['La Gaitana', 'Barrio'],
    ['El Rosario', 'Barrio'],
    ['El Jardín', 'Barrio'],
    ['El Obrero', 'Barrio'],
    ['Juan Pablo I', 'Barrio'],
    ['La Florida', 'Barrio'],
    ['Bosque de Cantabria', 'Urbanización'],
    ['Nueva Holanda', 'Urbanización'],
    ['Los Canelos', 'Barrio'],
    ['El Monasterio', 'Barrio'],
    ['Santa Clara', 'Barrio'],
    ['Nazareth', 'Barrio'],
    ['San Cayetano', 'Barrio'],
    ['Primavera', 'Barrio'],
    ['Calima', 'Barrio'],
    ['Los Andes', 'Barrio'],
    ['Los Laureles', 'Barrio'],
    ['Villa Laura', 'Barrio'],
    ['Ciudadela Sabambu', 'Barrio'],
    ['La Carolina', 'Barrio'],
    ['Jorge Enrique Pulido', 'Barrio'],
    ['Villa Sol', 'Barrio'],
    ['Villa Karol', 'Barrio'],
    ['Mega Colegio', 'Equipamiento/Referencia urbana'],
    ['Tochere', 'Condominio'],
    ['Bosque del Caracolí', 'Conjunto cerrado'],
    ['Torres de San Felipe', 'Proyecto de vivienda VIS'],
    ['Castalia', 'Sector'],
    ['Sagrada Familia', 'Urbanización'],
    ['Riveras de Garzón', 'Urbanización'],
    ['Nueva Floresta', 'Urbanización'],
    ['Prado Alto', 'Urbanización'],
    ['Reservas de Garzón', 'Urbanización'],
    ['San Sebastián', 'Urbanización'],
    ['La Floresta', 'Urbanización'],
    ['Los Comuneros', 'Barrio'],
    ['La Libertad', 'Barrio'],
    ['Veinte de Julio', 'Barrio'],
    ['Julio Bahamón', 'Barrio'],
    ['Chapinero', 'Barrio'],
    ['Granjas A', 'Barrio'],
    ['Los Nogales', 'Barrio'],
    ['Las Granjas', 'Barrio'],
    ['Limonar', 'Barrio'],
    ['Villa Garzón', 'Barrio'],
    ['Villas Café', 'Barrio'],
    ['Los Samanes', 'Barrio'],
    ['Villa Prado', 'Barrio'],
    ['Fundadores', 'Barrio'],
    ['Las Vegas', 'Barrio'],
    ['Aguazul', 'Barrio'],
    ['5 de Noviembre', 'Barrio'],
    ['Villa Constanza', 'Barrio'],
    ['Nuevo Horizonte', 'Barrio'],
    ['Los Guaduales III', 'Barrio'],
    ['Álamos', 'Barrio'],
    ['Nueva Colombia', 'Barrio'],
    ['Villa Francia', 'Barrio'],
    ['Villa Alejandra', 'Barrio'],
    ['Brisas del Sur', 'Barrio'],
    ['Villas del Café', 'Barrio'],
    ['Las Palmeras', 'Barrio'],
    ['Los Guaduales I', 'Barrio'],
    ['Los Guaduales II', 'Barrio'],
    ['La Fortaleza', 'Urbanización'],
    ['Cerros', 'Barrio'],
    ['Pío XII', 'Barrio'],
    ['El Bosque', 'Barrio'],
    ['Termitas', 'Barrio'],
    ['Minuto de Dios', 'Barrio'],
    ['Ciudad Real', 'Barrio'],
    ['El Universitario', 'Barrio'],
    ['Samaritanos', 'Barrio'],
    ['El Fontanar', 'Barrio'],
    ['Las Orquídeas', 'Barrio'],
    ['Santa Lucía', 'Barrio'],
    ['Canadá', 'Barrio'],
    ['María Auxiliadora', 'Barrio'],
    ['Luis Carlos Galán', 'Barrio'],
    ['Las Palmas', 'Barrio'],
    ['San José Residencial', 'Finca/Desarrollo residencial'],
    ['Reservas del Oriente', 'Urbanización'],
    ['Bosques del Café', 'Urbanización'],
    ['Octavio Martínez', 'Urbanización'],
    ['San Carlos', 'Urbanización'],
    ['Descanso', 'Corregimiento'],
    ['Filo de Guayabal', 'Vereda'],
    ['La Orquídea', 'Vereda'],
    ['El Descanso', 'Vereda'],
    ['Nuevo Horizonte', 'Vereda'],
    ['La Aurora', 'Vereda'],
    ['Los Robles', 'Vereda'],
    ['El Mesón', 'Corregimiento'],
    ['La Cabaña', 'Vereda'],
    ['El Mesón', 'Vereda'],
    ['Los Pinos', 'Vereda'],
    ['Las Mercedes', 'Vereda'],
    ['La Cañada', 'Vereda'],
    ['El Recreo', 'Corregimiento'],
    ['Primavera', 'Vereda'],
    ['Mesitas', 'Vereda'],
    ['Pan de Azúcar', 'Vereda'],
    ['El Recreo', 'Vereda'],
    ['La Jagua', 'Corregimiento'],
    ['La Jagua', 'Vereda'],
    ['Majo', 'Corregimiento'],
    ['Balseadero', 'Vereda'],
    ['Alto Sartenejo', 'Vereda'],
    ['Majo', 'Vereda'],
    ['El Barzal', 'Vereda'],
    ['Jagualito', 'Vereda'],
    ['Sector Huacanas', 'Sector de vereda'],
    ['Paraíso', 'Corregimiento'],
    ['Los Guaduales', 'Vereda'],
    ['Potrerillos', 'Vereda'],
    ['Filo de Pompeya', 'Vereda'],
    ['El Paraíso', 'Vereda'],
    ['Villa Hermosa', 'Vereda'],
    ['Buenos Aires', 'Vereda'],
    ['La Soledad', 'Vereda'],
    ['Monserrate', 'Vereda'],
    ['El Progreso', 'Vereda'],
    ['Las Brisas', 'Vereda'],
    ['Paloquemao', 'Vereda'],
    ['El Balseral', 'Vereda'],
    ['Los Milagros', 'Vereda'],
    ['San José', 'Vereda'],
    ['Providencia', 'Corregimiento'],
    ['San Rafael', 'Vereda'],
    ['La Florida', 'Vereda'],
    ['Sector Filo Rico', 'Sector de vereda'],
    ['Las Delicias', 'Vereda'],
    ['Vega de Platanares', 'Vereda'],
    ['El Líbano', 'Vereda'],
    ['Providencia', 'Vereda'],
    ['Filo de Platanares', 'Vereda'],
    ['Nueva Floresta', 'Vereda'],
    ['Caguancito', 'Corregimiento'],
    ['El Mirador', 'Vereda'],
    ['La Ulama', 'Vereda'],
    ['Caguancito', 'Vereda'],
    ['Mocoa', 'Vereda'],
    ['Puerto Alegría', 'Vereda'],
    ['Alto San Isidro', 'Vereda'],
    ['El Caguán', 'Vereda'],
    ['Panorama', 'Vereda'],
    ['El Socorro', 'Vereda'],
    ['San Antonio del Pescado', 'Corregimiento'],
    ['La Esperanza', 'Vereda'],
    ['La Trinidad', 'Vereda'],
    ['San Antonio', 'Vereda'],
    ['Sector Las Mercedes', 'Sector de vereda'],
    ['Unión Aguacaliente', 'Vereda'],
    ['El Viso', 'Vereda'],
    ['San Pedro', 'Vereda'],
    ['Sector La Ceiba', 'Sector de vereda'],
    ['El Rosario', 'Vereda'],
    ['San Luis', 'Vereda'],
    ['Campo Bello', 'Vereda'],
    ['Santa Helena', 'Vereda'],
    ['Albania', 'Vereda'],
    ['El Pescado', 'Vereda'],
    ['San Gerardo', 'Corregimiento'],
    ['Bellavista', 'Vereda'],
    ['San Gerardo', 'Vereda'],
    ['Las Palmitas', 'Vereda'],
    ['San Miguel', 'Vereda'],
    ['Alejandría', 'Vereda'],
    ['El Cedral', 'Vereda'],
    ['El Batán', 'Vereda'],
    ['Los Alpes', 'Vereda'],
    ['Santa Marta', 'Corregimiento'],
    ['Alto Fátima', 'Vereda'],
    ['Santa Marta', 'Vereda'],
    ['La Esmeralda', 'Vereda'],
    ['Los Sauces', 'Vereda'],
    ['Fátima', 'Vereda'],
    ['Claros', 'Vereda'],
    ['Puerto El Oasis', 'Vereda'],
    ['Agua Blanca', 'Vereda'],
    ['Villa Rica', 'Vereda'],
    ['Zuluaga', 'Corregimiento'],
    ['Miraflores', 'Vereda'],
    ['Los Medios', 'Vereda'],
    ['La Pita', 'Vereda'],
    ['La Azulita', 'Vereda'],
    ['Zuluaga', 'Vereda'],
    ['Zuluaguita', 'Vereda'],
    ['Villa Florida', 'Vereda'],
    ['El Vergel', 'Vereda'],
    ['Cristo Rey', 'Barrio'],
    ['Nueva Esperanza Real', 'Barrio'],
    ['San Lorenzo', 'Barrio'],
    ['Alto Garzón', 'Asentamiento'],
    ['Brisas del Oriente', 'Asentamiento'],
    ['Pastranista e Israelitas', 'Asentamiento'],
    ['San Felipe', 'Asentamiento'],
];

/** Clasificaciones rurales (el resto son del casco urbano). */
const ZONAS_CLASES_RURALES = ['Corregimiento', 'Vereda', 'Sector de vereda'];
